/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:12452b7f-cba3-4e5b-b5b0-c383702396d9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oVW3G6zGi",
    "aws_user_pools_web_client_id": "648jh7q31uneitkqb3qllg77vi",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://n7ir2tnpmvdern46fklzqkqb4y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jimkuweqkvggbbgu3sdpvybycu",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "fitness2002-dev",
            "region": "us-east-1"
        }
    ],
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_3DT06CGeX",
        "userPoolWebClientId": "2f5km20kqd384qfq6mdja7q3e5",
        "identityPoolId": "us-east-1:fbb405c2-43a5-4cd8-af56-d4a88b075e6b",
        "mandatorySignIn": true,
        "authenticationFlowType": "USER_SRP_AUTH",
        "oauth": {
            "domain": "fitness.auth.us-east-1.amazoncognito.com",
            "scope": [
                "email",
                "openid",
                "profile"
            ],
            "redirectSignIn": "http://localhost:5173/",
            "redirectSignOut": "http://localhost:5173/",
            "responseType": "code"
        }
    },
    "API": {
        "endpoints": [
            {
                "name": "GraphQL",
                "endpoint": "https://aimtngr7hbcwpp7blalkcrtrja.appsync-api.us-east-1.amazonaws.com/graphql",
                "region": "us-east-1"
            }
        ]
    }
};


export default awsmobile;
